# Generated by Django 6.0.3 on 2026-06-23 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
